/**
 * Stop-hook install/remove for Claude Code settings files (design §3.1, §3.3).
 *
 * The settings command is shell-dialect-free by construction:
 *   node "<absolute path>/whydone-hook.cjs"
 * — a bare program + one double-quoted absolute argument, which parses
 * identically under sh, bash, Git Bash, cmd.exe, and PowerShell. All guard
 * logic (project-dir resolution, whydone-present check, fail-open) lives in
 * the launcher's JavaScript, not in shell semantics.
 *
 * Write-back care (§3.3 step 4): settings files are live — Claude Code itself
 * writes settings.local.json mid-session. Guards:
 *  - Optimistic-lock write: stat before write; if the file changed since the
 *    read, re-read and re-apply the mutation once; a second change ⇒ 'conflict',
 *    touch nothing. Read→mutate→write uses sync fs — no intervening awaits.
 *  - Formatting preservation: serialize with the file's own detected
 *    indentation (first ^[ \t]+ match; default two spaces) and preserve
 *    presence/absence of a trailing newline. Key order is preserved because
 *    the mutation edits the parsed object in place.
 */

import { existsSync, mkdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import path from 'node:path'

/** Marker substring for surgical uninstall — lives inside handler.command. */
export const HOOK_MARKER = 'whydone-hook.cjs'

/** Basename of the init-written launcher file (project or global .claude/). */
export const LAUNCHER_BASENAME = 'whydone-hook.cjs'

export type InstallHookResult = 'installed' | 'updated' | 'invalid-json' | 'conflict'
export type RemoveHookResult = 'removed' | 'absent' | 'invalid-json' | 'conflict'

/** Test seam: called between serialize and the pre-write stat re-check. */
export const _testSeams: { beforeWrite?: () => void } = {}

interface HookHandler {
  type?: unknown
  command?: unknown
  timeout?: unknown
  [key: string]: unknown
}

interface StopGroup {
  hooks?: unknown
  [key: string]: unknown
}

/** The settings command: `node "<launcherPath>"` — platform-native absolute path. */
export function buildHookCommand(launcherPath: string): string {
  return `node "${launcherPath}"`
}

/**
 * The §3.1 launcher body — deterministic bytes, no machine-specific paths.
 * CJS so it runs regardless of any surrounding package.json "type" field.
 * Behavior, pinned:
 *  1. Everything ends in `finally { process.exit(0) }` — the launcher CANNOT
 *     exit non-zero (this replaces `|| true` with something no shell dialect
 *     can break).
 *  2. projectDir = CLAUDE_PROJECT_DIR || cwd.
 *  3. Fast no-op guards BEFORE loading anything heavy: existsSync('.whydone')
 *     miss ⇒ exit 0; require.resolve('whydone/package.json') miss ⇒ exit 0.
 *  4. Read stdin fully, spawnSync the CLI with an 8 s timeout, forward child
 *     stdout only on clean success. Any error/timeout ⇒ exit 0.
 */
export function buildLauncherSource(): string {
  return `#!/usr/bin/env node
/* whydone Stop-hook launcher — machine-generated by \`whydone init\`.
 * Runs \`whydone hook stop\` for the current project and exits 0 on every
 * path, so a hook failure can never block the user. Safe to delete;
 * \`npx whydone uninstall\` removes it and its settings.json entry. */
'use strict'
try {
  main()
} catch {
  /* fail open */
} finally {
  process.exit(0)
}

function main() {
  const fs = require('node:fs')
  const path = require('node:path')
  const { spawnSync } = require('node:child_process')

  const projectDir = process.env.CLAUDE_PROJECT_DIR || process.cwd()

  // Fast no-op: not a whydone project — one existsSync, no CLI load.
  if (!fs.existsSync(path.join(projectDir, '.whydone'))) return

  // Resolve the CLI from the project (handles hoisting/pnpm). Whydone
  // removed from node_modules => permanent silence, zero transcript noise.
  let pkgPath
  try {
    pkgPath = require.resolve('whydone/package.json', { paths: [projectDir] })
  } catch {
    return
  }
  const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'))
  const bin = typeof pkg.bin === 'string' ? pkg.bin : (pkg.bin && pkg.bin.whydone) || 'dist/cli.js'
  const cliJs = path.join(path.dirname(pkgPath), bin)

  let input = ''
  try {
    input = fs.readFileSync(0, 'utf8')
  } catch {
    input = ''
  }

  const r = spawnSync(process.execPath, [cliJs, 'hook', 'stop'], {
    input,
    cwd: projectDir,
    timeout: 8000,
    encoding: 'utf8',
  })
  if (!r.error && r.status === 0 && r.stdout) process.stdout.write(r.stdout)
}
`
}

function isMarkerHandler(h: HookHandler): boolean {
  return (
    h !== null &&
    typeof h === 'object' &&
    h.type === 'command' &&
    typeof h.command === 'string' &&
    h.command.includes(HOOK_MARKER)
  )
}

interface Snapshot {
  raw: string | null // null = file absent
  mtimeMs: number
  size: number
}

function takeSnapshot(settingsPath: string): Snapshot {
  try {
    const raw = readFileSync(settingsPath, 'utf-8')
    const st = statSync(settingsPath)
    return { raw, mtimeMs: st.mtimeMs, size: st.size }
  } catch {
    return { raw: null, mtimeMs: -1, size: -1 }
  }
}

function fileChangedSince(settingsPath: string, snap: Snapshot): boolean {
  try {
    const st = statSync(settingsPath)
    return snap.raw === null || st.mtimeMs !== snap.mtimeMs || st.size !== snap.size
  } catch {
    return snap.raw !== null // existed before, gone now
  }
}

function detectIndent(raw: string | null): string {
  if (raw === null) return '  '
  const m = /^[ \t]+/m.exec(raw)
  return m ? m[0] : '  '
}

function serialize(obj: Record<string, unknown>, snap: Snapshot): string {
  const body = JSON.stringify(obj, null, detectIndent(snap.raw))
  const trailingNewline = snap.raw === null ? true : snap.raw.endsWith('\n')
  return trailingNewline ? body + '\n' : body
}

type ParsedSettings =
  | { ok: true; obj: Record<string, unknown> }
  | { ok: false }

function parseSettings(snap: Snapshot): ParsedSettings {
  if (snap.raw === null) return { ok: true, obj: {} }
  try {
    const parsed: unknown = JSON.parse(snap.raw)
    if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) return { ok: false }
    return { ok: true, obj: parsed as Record<string, unknown> }
  } catch {
    return { ok: false }
  }
}

/** Every handler object across all Stop groups (lenient about odd shapes). */
function stopHandlers(obj: Record<string, unknown>): HookHandler[] {
  const hooks = obj.hooks
  if (typeof hooks !== 'object' || hooks === null || Array.isArray(hooks)) return []
  const stop = (hooks as Record<string, unknown>).Stop
  if (!Array.isArray(stop)) return []
  const out: HookHandler[] = []
  for (const group of stop as StopGroup[]) {
    if (group === null || typeof group !== 'object' || !Array.isArray(group.hooks)) continue
    for (const h of group.hooks as HookHandler[]) out.push(h)
  }
  return out
}

/** True when a whydone marker handler exists in the file's Stop hooks. */
export async function hasStopHook(settingsPath: string): Promise<boolean> {
  const parsed = parseSettings(takeSnapshot(settingsPath))
  if (!parsed.ok) return false
  return stopHandlers(parsed.obj).some(isMarkerHandler)
}

/**
 * Install (or refresh) the whydone Stop hook into a settings file.
 * Strict JSON read-modify-write; parse failure ⇒ 'invalid-json', touch nothing.
 */
export async function installStopHook(
  settingsPath: string,
  launcherPath: string,
): Promise<InstallHookResult> {
  const command = buildHookCommand(launcherPath)

  for (let attempt = 0; attempt < 2; attempt++) {
    const snap = takeSnapshot(settingsPath)
    const parsed = parseSettings(snap)
    if (!parsed.ok) return 'invalid-json'
    const obj = parsed.obj

    // Ensure hooks.Stop exists (never clobber a non-object hooks value).
    if (obj.hooks === undefined) obj.hooks = {}
    const hooks = obj.hooks
    if (typeof hooks !== 'object' || hooks === null || Array.isArray(hooks)) return 'invalid-json'
    const hooksObj = hooks as Record<string, unknown>
    if (hooksObj.Stop === undefined) hooksObj.Stop = []
    if (!Array.isArray(hooksObj.Stop)) return 'invalid-json'

    let changed = false
    let result: InstallHookResult
    const marker = stopHandlers(obj).find(isMarkerHandler)
    if (marker !== undefined) {
      // Refresh command in place if the launcher path changed.
      if (marker.command !== command) {
        marker.command = command
        changed = true
      }
      // Preserve a user-modified positive numeric timeout (§3.3 step 3);
      // only an absent/invalid timeout is reset to 10.
      if (!(typeof marker.timeout === 'number' && marker.timeout > 0)) {
        marker.timeout = 10
        changed = true
      }
      result = 'updated'
    } else {
      ;(hooksObj.Stop as unknown[]).push({
        hooks: [{ type: 'command', command, timeout: 10 }],
      })
      changed = true
      result = 'installed'
    }

    if (!changed) return result

    const out = serialize(obj, snap)
    _testSeams.beforeWrite?.()
    if (fileChangedSince(settingsPath, snap)) continue // re-read and re-apply once
    mkdirSync(path.dirname(settingsPath), { recursive: true })
    writeFileSync(settingsPath, out, 'utf-8')
    return result
  }
  return 'conflict'
}

/**
 * Remove every whydone marker handler from the settings file's Stop groups.
 * Prunes groups whose hooks became empty, drops Stop if empty, drops hooks if
 * empty. Writes back only if anything changed. Never deletes the file itself.
 */
export async function removeStopHook(settingsPath: string): Promise<RemoveHookResult> {
  for (let attempt = 0; attempt < 2; attempt++) {
    const snap = takeSnapshot(settingsPath)
    if (snap.raw === null) return 'absent'
    const parsed = parseSettings(snap)
    if (!parsed.ok) return 'invalid-json'
    const obj = parsed.obj

    const hooks = obj.hooks
    if (typeof hooks !== 'object' || hooks === null || Array.isArray(hooks)) return 'absent'
    const hooksObj = hooks as Record<string, unknown>
    const stop = hooksObj.Stop
    if (!Array.isArray(stop)) return 'absent'

    let changed = false
    const keptGroups: unknown[] = []
    for (const group of stop as StopGroup[]) {
      if (group === null || typeof group !== 'object' || !Array.isArray(group.hooks)) {
        keptGroups.push(group)
        continue
      }
      const keptHandlers = (group.hooks as HookHandler[]).filter((h) => !isMarkerHandler(h))
      if (keptHandlers.length !== (group.hooks as HookHandler[]).length) {
        changed = true
        if (keptHandlers.length === 0) continue // drop the now-empty group
        group.hooks = keptHandlers
      }
      keptGroups.push(group)
    }

    if (!changed) return 'absent'

    if (keptGroups.length === 0) {
      delete hooksObj.Stop
    } else {
      hooksObj.Stop = keptGroups
    }
    if (Object.keys(hooksObj).length === 0) {
      delete obj.hooks
    }

    const out = serialize(obj, snap)
    _testSeams.beforeWrite?.()
    if (fileChangedSince(settingsPath, snap)) continue
    writeFileSync(settingsPath, out, 'utf-8')
    return 'removed'
  }
  return 'conflict'
}

/** Convenience: does the launcher file exist at the scope's .claude/ dir? */
export function launcherExists(claudeDir: string): boolean {
  return existsSync(path.join(claudeDir, LAUNCHER_BASENAME))
}
